function bgspreadsheet = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  BGSPREADSHEET = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  BGSPREADSHEET = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  BGSPREADSHEET = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  bgspreadsheet = importfile("G:\Models\COPSE-main\new_forcings\bgspreadsheet.xlsx", "Sheet 1", [1, 34]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Feb-2023 11:07:19

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 36];
end

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 24);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["oxygen", "Var2", "Var3", "Var4", "Var5", "fireBionorm", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "photoBionorm", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "bothBionorm"];
opts.SelectedVariableNames = ["oxygen", "fireBionorm", "photoBionorm", "bothBionorm"];
opts.VariableTypes = ["double", "char", "char", "char", "char", "double", "char", "char", "char", "char", "char", "char", "char", "char", "double", "char", "char", "char", "char", "char", "char", "char", "char", "double"];
opts = setvaropts(opts, [2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23], "EmptyFieldRule", "auto");

% Import the data
bgspreadsheet = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    bgspreadsheet = [bgspreadsheet; tb]; %#ok<AGROW>
end

end